# Generated by Django 4.2.5 on 2023-10-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0002_remove_studentmodel_crdt_studentmodel_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='rno',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='roll_no',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='marks',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
