# Generated by Django 4.2.5 on 2023-10-29 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0003_remove_studentmodel_rno_studentmodel_roll_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='upload_file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
