# Generated by Django 4.2.5 on 2023-10-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0004_studentmodel_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='upload_file',
            field=models.FileField(upload_to=''),
        ),
    ]
