# Generated by Django 4.2.5 on 2023-10-29 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0006_alter_studentmodel_marks_alter_studentmodel_roll_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='Department_Name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
